-- AlterTable
ALTER TABLE `income_profiles` ADD COLUMN `business_top3_customers` TEXT NULL,
    ADD COLUMN `business_top3_suppliers` TEXT NULL,
    ADD COLUMN `crop_production_profile` TEXT NULL,
    ADD COLUMN `farm_risk_assessment` VARCHAR(80) NULL,
    ADD COLUMN `ofw_account_number` VARCHAR(80) NULL,
    ADD COLUMN `ofw_agency_address` TEXT NULL,
    ADD COLUMN `ofw_alternate_email` VARCHAR(160) NULL,
    ADD COLUMN `ofw_authorized_representative` VARCHAR(160) NULL,
    ADD COLUMN `ofw_bank_branch` VARCHAR(120) NULL,
    ADD COLUMN `ofw_dmwi_license` VARCHAR(120) NULL,
    ADD COLUMN `ofw_email` VARCHAR(160) NULL,
    ADD COLUMN `ofw_facebook` VARCHAR(160) NULL,
    ADD COLUMN `ofw_gcash_number` VARCHAR(40) NULL,
    ADD COLUMN `ofw_name` VARCHAR(160) NULL,
    ADD COLUMN `ofw_pagibig_status` VARCHAR(40) NULL,
    ADD COLUMN `ofw_philhealth_status` VARCHAR(40) NULL,
    ADD COLUMN `ofw_recruitment_agency` VARCHAR(160) NULL,
    ADD COLUMN `ofw_rep_complete_address` TEXT NULL,
    ADD COLUMN `ofw_rep_relationship` VARCHAR(120) NULL,
    ADD COLUMN `ofw_sss_status` VARCHAR(40) NULL,
    ADD COLUMN `ofw_total_years` DECIMAL(5, 2) NULL,
    ADD COLUMN `owwa_membership` VARCHAR(40) NULL,
    ADD COLUMN `owwa_no` VARCHAR(80) NULL,
    ADD COLUMN `pension_account_number` VARCHAR(80) NULL,
    ADD COLUMN `pension_bank_branch` VARCHAR(120) NULL,
    ADD COLUMN `pension_deceased_member` VARCHAR(160) NULL,
    ADD COLUMN `pension_notes` TEXT NULL,
    ADD COLUMN `pension_sss_gsis_no` VARCHAR(80) NULL,
    MODIFY `pension_start_date` DATE NULL;
